apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
- ../../base

# CI rewrites newName/newTag on every build (kustomize edit set image).
# CHANGE_ME = your GitHub username (lowercase). The first CI run will
# overwrite these values automatically.
images:
- name: devops-poc-api
  newName: ghcr.io/azeem261/devops-poc-api
  newTag: 611b852daa9dbf8c83c188c70f67d086d31184f3
- name: devops-poc-frontend
  newName: ghcr.io/azeem261/devops-poc-frontend
  newTag: 611b852daa9dbf8c83c188c70f67d086d31184f3
- name: devops-poc-stats
  newName: ghcr.io/azeem261/devops-poc-stats
  newTag: 38cc063e78e15b2c15ac0149c66a5a479fb9aa03
- name: devops-poc-worker
  newName: ghcr.io/azeem261/devops-poc-worker
  newTag: 611b852daa9dbf8c83c188c70f67d086d31184f3
