apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
- ../../base

# CI rewrites newName/newTag on every build (kustomize edit set image).
# CHANGE_ME = your GitHub username (lowercase). The first CI run will
# overwrite these values automatically.
images:
- name: devops-poc-api
  newName: ghcr.io/azeem261/devops-poc-api
  newTag: 6252d665bb5fcf3fb1fb1cc554d97cafb87d7127
- name: devops-poc-frontend
  newName: ghcr.io/azeem261/devops-poc-frontend
  newTag: 6252d665bb5fcf3fb1fb1cc554d97cafb87d7127
- name: devops-poc-loadgen
  newName: ghcr.io/azeem261/devops-poc-loadgen
  newTag: 6252d665bb5fcf3fb1fb1cc554d97cafb87d7127
- name: devops-poc-stats
  newName: ghcr.io/azeem261/devops-poc-stats
  newTag: 6252d665bb5fcf3fb1fb1cc554d97cafb87d7127
- name: devops-poc-worker
  newName: ghcr.io/azeem261/devops-poc-worker
  newTag: 6252d665bb5fcf3fb1fb1cc554d97cafb87d7127
