apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow

resources:
- ../../base

# CI rewrites newName/newTag on every build (kustomize edit set image).
# CHANGE_ME = your GitHub username (lowercase). The first CI run will
# overwrite these values automatically.
images:
- name: devops-poc-api
  newName: ghcr.io/azeem261/devops-poc-api
  newTag: 695413f6749de45c03bc1563b1845e832582d435
- name: devops-poc-frontend
  newName: ghcr.io/azeem261/devops-poc-frontend
  newTag: 695413f6749de45c03bc1563b1845e832582d435
- name: devops-poc-worker
  newName: ghcr.io/azeem261/devops-poc-worker
  newTag: 695413f6749de45c03bc1563b1845e832582d435
